AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.3
Rails:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/environments/*
