AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.3

Rails:
  Enabled: true
Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/environments/*
