# Ruby DevCrea customize
FROM devcrea/base-rails

# Name of Project
ENV PROJECT dinin

# Prepare container
RUN mkdir /$PROJECT
WORKDIR /$PROJECT

# Téléchargement des dépandences
ADD Gemfile* /$PROJECT/

# Execute gems install
RUN bundle install --without production local

# Add files
ADD . /$PROJECT
