development:
  sessions:
    default:
      database: DEVCREA_dinin_dev
      hosts:
        - database
      options:
  options:
    raise_not_found_error: false
production:
  sessions:
    default:
      database: DEVCREA_dinin_prod
      hosts:
        - devcrea-db
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
test:
  sessions:
    default:
      database: DEVCREA_dinin_test
      hosts:
        - database
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
